version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: support_queue_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_queue_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"